### PR TITLE
Add animated slide-in and fix "modal bottom sheet" functionality

### PR DESCRIPTION
**Pull request by emanguy**
Fixes:
- Some spelling
- Issue where clicking an option on the bottom sheet, clicking outside the bottom sheet, or pressing the escape key would prevent the intended functionality of removing the paper-bottom-sheet from the DOM.
- Change of "model" to "modal" which fixes modal bottom sheet behavior

Additions:
- "slide" attribute which causes the bottom sheet to animate its entrance from the bottom of the screen
- Add documentation for open() and close() functions
- Add checkbox toggles for the "slide" and "modal" attributes in the demo

Behavioral changes:
- Setting the "modal" attribute will reveal the "cancel" option as the last option in the bottom sheet. When the paper dialog is not modal, the "cancel" option is hidden. In the non-modal case, the cancel option is redundant due to the fact that the user can click or tap outside the bottom sheet to hide/cancel it.

EDIT: demo from my repository at http://emanguy.github.io/paper-bottom-sheet.

EDIT 2: you'll have to update your readme so it doesn't point to mine when you merge

### CODE REVIEW

**Comment by ankon** [comment]
Sorry for the broken builds, this was caused by our .travis.yml. I hopefully fixed that with https://github.com/Collaborne/paper-bottom-sheet/commit/58bb214e4758843e39e97905beee0dd67283315b

**Comment by emanguy** [comment]
I'll merge your changes from master and see if the build succeeds. The build is passing on my repository, so it might just be because the code is in the pull request.

**Comment by emanguy** [comment]
Looks like that did it. Merge away.

**Comment by ronnyroeller** [comment]
Merged and released as 1.1.0.

Thanks a lot for your contributions, @emanguy

**Pull request merged**
